apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    jenkins_url: "http://outokumpu.com"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx