apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-test
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: pod-secrets
