apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 9376 # container port
