apiVersion: v1
kind: service
metadata:
  name: nginx-nodepod
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environment: dev
    purpose: node-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
