apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    environment: dev
    purpose: node-loadbalancer
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30007 # Correct camelCase
